import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Anonymous_Pro } from 'next/font/google';
import { Inter } from 'next/font/google';
import Navbar from "./Components/Navbar";

export const interSemiBold = Inter({
  subsets: ['latin'],
  weight: ['600'], // '600' corresponds to Semi-Bold
  variable: '--font-inter-semibold', // Optional: Define a CSS variable
});
export const anonymousPro = Anonymous_Pro({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-anonymous-pro', // Define a CSS variable name
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
